name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master

    - name: Copy index.html to EC2
      run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ github.workspace }}/index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

    - name: SSH into EC2 and restart Apache
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo service httpd restart
