name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo cp -f /var/www/html/index.html /var/www/html/index.html.bak  # Backup the existing HTML file
          sudo cp -f index.html /var/www/html/index.html  # Assuming your HTML file is in the root of the repository
          
  
          sudo service apache2 restart || sudo service httpd restart || true
